package com.ProjectSpringboot.Point_of_sale.service.IMPL;
import com.ProjectSpringboot.Point_of_sale.dto.request.CustomerDTO;
import com.ProjectSpringboot.Point_of_sale.dto.request.CustomerUpdateDTO;
import com.ProjectSpringboot.Point_of_sale.entity.Customer;
import com.ProjectSpringboot.Point_of_sale.exception.NotFoundException;
import com.ProjectSpringboot.Point_of_sale.repo.CustomerRepo;
import com.ProjectSpringboot.Point_of_sale.service.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;


@Service
public class CustomerServiceIMPL implements CustomerService{
    @Autowired
    private CustomerRepo customerRepo;

    @Transactional
    @Override
    public String saveCustomer(CustomerDTO customerDTO) {
        // customerId is auto-generated by CustomerIdGenerator (CUS-1000, CUS-1001, ...)
        Customer customer = new Customer(
                customerDTO.getCustomerName()
                , customerDTO.getCustomerAddress()
                , customerDTO.getCustomerContact()
                , customerDTO.getCustomerSalary()
                , customerDTO.getCustomerNic()
                , customerDTO.getActiveState()
        );
        customerRepo.save(customer);
        return customerDTO.getCustomerName();
    }

    @Transactional
    @Override
    public String updateCustomer(CustomerUpdateDTO customerUpdateDTO) {
        Customer customer = customerRepo.findById(customerUpdateDTO.getCustomerId()).orElse(null);
        if (customer != null) {
            customer.setCustomerName(customerUpdateDTO.getCustomerName());
            customer.setCustomerAddress(customerUpdateDTO.getCustomerAddress());
            customer.setCustomerContact(customerUpdateDTO.getCustomerContact());
            customerRepo.save(customer);
        }
        return "Updated Customer Successfully";
    }

    @Override
    public CustomerDTO getCustomerById(String customerId) {
        Customer customer = customerRepo.findById(customerId)
                .orElseThrow(() -> new NotFoundException("Customer not found with ID: " + customerId));
        return new CustomerDTO(
                customer.getCustomerId(),
                customer.getCustomerName(),
                customer.getCustomerAddress(),
                customer.getCustomerContact(),
                customer.getCustomerSalary(),
                customer.getCustomerNic(),
                customer.getActiveState()
        );
    }
    @Override
    public List<CustomerDTO> getAllCustomers() {
        List<Customer> customers = customerRepo.findAll();
        if(customers.isEmpty()) {
            throw new NotFoundException("No any customers");
        }else{
        List<CustomerDTO> customerDTOs = new ArrayList<>();
        for (Customer customer : customers) {
            CustomerDTO customerDTO = new CustomerDTO(
                    customer.getCustomerId(),
                    customer.getCustomerName(),
                    customer.getCustomerAddress(),
                    customer.getCustomerContact(),
                    customer.getCustomerSalary(),
                    customer.getCustomerNic(),
                    customer.getActiveState()
            );
            customerDTOs.add(customerDTO);
        }
        return customerDTOs;
        }
    }

    @Override
    public void deleteCustomerById(String customerId) {
        if (!customerRepo.existsById(customerId)) {
            throw new NotFoundException("Customer not found with ID: " + customerId);
        }
        customerRepo.deleteById(customerId);
    }

    @Override
    public List<CustomerDTO> getAllCustomersbyactivestate(boolean activeState) {
        List<Customer> customers = customerRepo.findByActiveState(activeState ? 1 : 0);
        List<CustomerDTO> customerDTOs = new ArrayList<>();
        for (Customer customer : customers) {
            CustomerDTO customerDTO = new CustomerDTO(
                    customer.getCustomerId(),
                    customer.getCustomerName(),
                    customer.getCustomerAddress(),
                    customer.getCustomerContact(),
                    customer.getCustomerSalary(),
                    customer.getCustomerNic(),
                    customer.getActiveState()
            );
            customerDTOs.add(customerDTO);
        }
        return customerDTOs;
    }




}
